apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-trbovlje
resources:
  - parladata/deployment.yaml
  - parladata/ingress.yaml
  - parladata/pvc.yaml
  - parladata/service.yaml
  - parladata/solr.yaml
  # uncomment cronjob to enable it
  - parladata/cronjobs/task_runner_cronjob.yaml
  - parladata/cronjobs/optimu_import_cronjob.yaml

  - parlacards/deployment.yaml
  - parlacards/ingress.yaml
  - parlacards/service.yaml

  - parlasite/deployment.yaml
  - parlasite/ingress.yaml
  - parlasite/service.yaml

  - parlassets/deployment.yaml
  - parlassets/ingress.yaml
  - parlassets/service.yaml
images:
  - name: parladata-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parladata-trbovlje
    newTag: '7251431e560ee61134ee01a6ba9d8693500a59fe'
  - name: parlasolr-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlasolr-trbovlje
    newTag: '7251431e560ee61134ee01a6ba9d8693500a59fe'
  - name: parlacards-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlacards-trbovlje
    newTag: '7251431e560ee61134ee01a6ba9d8693500a59fe'
  - name: parlasite-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlasite-trbovlje
    newTag: '7251431e560ee61134ee01a6ba9d8693500a59fe'
  - name: parlassets-trbovlje
    newName: rg.fr-par.scw.cloud/djnd/parlassets-trbovlje
    newTag: '7251431e560ee61134ee01a6ba9d8693500a59fe'
