apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-hrastnik
resources:
  - parladata/deployment.yaml
  - parladata/ingress.yaml
  - parladata/pvc.yaml
  - parladata/service.yaml
  - parladata/solr.yaml
  # uncomment cronjob to enable it
  # - parladata/cronjobs/task_runner_cronjob.yaml

  - parlacards/deployment.yaml
  - parlacards/ingress.yaml
  - parlacards/service.yaml

  - parlasite/deployment.yaml
  - parlasite/ingress.yaml
  - parlasite/service.yaml
  - parlasite-2022/deployment.yaml
  - parlasite-2022/ingress.yaml
  - parlasite-2022/service.yaml
  - parlassets/deployment.yaml
  - parlassets/ingress.yaml
  - parlassets/service.yaml
images:
  - name: parladata-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parladata-hrastnik
    newTag: 'b26d8cc90f3936ffa9c0f493ddf030f69810c258'
  - name: parlasolr-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlasolr-hrastnik
    newTag: 'b26d8cc90f3936ffa9c0f493ddf030f69810c258'
  - name: parlacards-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlacards-hrastnik
    newTag: 'b26d8cc90f3936ffa9c0f493ddf030f69810c258'
  - name: parlasite-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlasite-hrastnik
    newTag: 'b26d8cc90f3936ffa9c0f493ddf030f69810c258'
  - name: parlassets-hrastnik
    newName: rg.fr-par.scw.cloud/djnd/parlassets-hrastnik
    newTag: 'b26d8cc90f3936ffa9c0f493ddf030f69810c258'
