apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ajdovscina
resources:
  - parladata/deployment.yaml
  - parladata/ingress.yaml
  - parladata/pvc.yaml
  - parladata/service.yaml
  - parladata/solr.yaml
  # uncomment cronjob to enable it
  # - parladata/cronjobs/task_runner_cronjob.yaml

  - parlacards/deployment.yaml
  - parlacards/ingress.yaml
  - parlacards/service.yaml

  - parlasite/deployment.yaml
  - parlasite/ingress.yaml
  - parlasite/service.yaml
  - parlasite-2022/deployment.yaml
  - parlasite-2022/ingress.yaml
  - parlasite-2022/service.yaml
  - parlassets/deployment.yaml
  - parlassets/ingress.yaml
  - parlassets/service.yaml
images:
  - name: parladata-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parladata-ajdovscina
    newTag: '5444dc48ef6c6e1b0488c9c41808ef79ca1c17f3'
  - name: parlasolr-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlasolr-ajdovscina
    newTag: '5444dc48ef6c6e1b0488c9c41808ef79ca1c17f3'
  - name: parlacards-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlacards-ajdovscina
    newTag: '5444dc48ef6c6e1b0488c9c41808ef79ca1c17f3'
  - name: parlasite-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlasite-ajdovscina
    newTag: '5444dc48ef6c6e1b0488c9c41808ef79ca1c17f3'
  - name: parlassets-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlassets-ajdovscina
    newTag: '5444dc48ef6c6e1b0488c9c41808ef79ca1c17f3'
