# Generated by Django 5.2.17 on 2026-08-26 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0095_alter_proceduretype_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="The summary text of the law or legislation.",
                        null=True,
                        verbose_name="Text",
                    ),
                ),
                (
                    "ai_model",
                    models.TextField(
                        blank=True,
                        help_text="The AI model associated with the summary.",
                        null=True,
                        verbose_name="Model",
                    ),
                ),
                (
                    "ai_model_version",
                    models.TextField(
                        blank=True,
                        help_text="The version of the AI model associated with the summary.",
                        null=True,
                        verbose_name="Model Version",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the summary has been approved.",
                        verbose_name="Is Approved",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        help_text="The link associated with the summary.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parladata.link",
                        verbose_name="Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Summary",
                "verbose_name_plural": "Summaries",
            },
        ),
    ]
