# Generated by Django 5.2.17 on 2026-08-26 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parladata", "0096_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="summary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                help_text="The time the object was created.",
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summary",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="The time the object was last updated.",
                verbose_name="updated_at",
            ),
        ),
    ]
